//! Generated-file detection via compiled regex patterns.
//!
//! `is_generated_file(path)` returns `true` when the file path matches patterns
//! known to indicate tool-generated source. Used to downrank generated files in
//! edge resolution (`select_best_candidate`) and MCP output assembly so hand-written
//! implementations surface first.
//!
//! Detection is path-only (O(1) per file, no I/O) — content-based heuristics
//! (e.g. `// Code generated by`) are deferred to a future version.

use regex::RegexSet;
use std::sync::LazyLock;

/// Compiled set of patterns matching tool-generated file paths across all
/// supported language families.
static GENERATED_PATTERNS: LazyLock<RegexSet> = LazyLock::new(|| {
    RegexSet::new([
        // Go: protobuf, gRPC, mockgen, stringer, ent, wire, sqlc, oapi-codegen
        r"\.pb\.go$",
        r"_grpc\.pb\.go$",
        r"_mock\.go$",
        r"mock_[^/\\]+\.go$",
        r"_string\.go$",
        r"_gen\.go$",
        r"wire_gen\.go$",
        r"ent/[^/\\]+\.go$",
        r"zzgenerated[^/\\]*\.go$",
        r"zz_generated[^/\\]*\.go$",
        // TS/JS: compiled output, bundler artifacts, generated GraphQL/OpenAPI
        r"\.generated\.(ts|js|tsx|jsx)$",
        r"\.g\.(ts|js)$",
        r"__generated__/",
        r"generated/[^/\\]+\.(ts|js|tsx|jsx)$",
        r"dist/[^/\\]+\.(js|mjs|cjs)$",
        r"\.next/",
        r"\.nuxt/",
        // Python: protobuf, gRPC, pydantic codegen, alembic migrations
        r"_pb2\.py$",
        r"_pb2_grpc\.py$",
        r"_generated\.py$",
        // C/C++: protobuf, flex/bison, moc (Qt), uic (Qt)
        r"\.pb\.(h|cc|cpp)$",
        r"\.grpc\.pb\.(h|cc|cpp)$",
        r"moc_[^/\\]+\.cpp$",
        r"ui_[^/\\]+\.h$",
        r"\.tab\.(c|h)$",
        r"lex\.yy\.c$",
        // C#: generated designer files, EF migrations, auto-generated
        r"\.Designer\.cs$",
        r"\.g\.cs$",
        r"\.generated\.cs$",
        r"Migrations/[^/\\]+\.cs$",
        // Java: annotation processors, protobuf, generated sources
        r"generated-sources/",
        r"target/generated/",
        r"build/generated/",
        // Swift: generated mocks, sourcery output
        r"\.generated\.swift$",
        r"Generated/[^/\\]+\.swift$",
        // Dart: freezed, json_serializable, build_runner output
        r"\.g\.dart$",
        r"\.freezed\.dart$",
        // Rust: build script output (OUT_DIR patterns)
        r"target/[^/\\]+/build/",
        // General: vendor directories, node_modules, lock files
        r"vendor/",
        r"node_modules/",
        r"__pycache__/",
    ])
    .expect("generated-file regex patterns must compile")
});

/// Returns `true` if `path` matches any known generated-file pattern.
///
/// The check is O(1) amortized (compiled regex set, single pass). No I/O.
/// Path separators are normalized to `/` before matching so patterns work
/// cross-platform.
pub fn is_generated_file(path: &str) -> bool {
    // Normalize Windows backslashes for consistent matching.
    let normalized: std::borrow::Cow<'_, str> = if path.contains('\\') {
        std::borrow::Cow::Owned(path.replace('\\', "/"))
    } else {
        std::borrow::Cow::Borrowed(path)
    };
    GENERATED_PATTERNS.is_match(&normalized)
}

// ─── Tests ───────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // --- Positive cases (should be detected as generated) ---

    #[test]
    fn go_protobuf() {
        assert!(is_generated_file("pkg/api/v1/service.pb.go"));
        assert!(is_generated_file("api/service_grpc.pb.go"));
    }

    #[test]
    fn go_mock_and_gen() {
        assert!(is_generated_file("internal/repo/repo_mock.go"));
        assert!(is_generated_file("mock_repository.go"));
        assert!(is_generated_file("pkg/wire_gen.go"));
        assert!(is_generated_file("internal/status_string.go"));
        assert!(is_generated_file("internal/something_gen.go"));
        assert!(is_generated_file("ent/user.go"));
        assert!(is_generated_file("pkg/zzgenerated_defaults.go"));
        assert!(is_generated_file("pkg/zz_generated_deepcopy.go"));
    }

    #[test]
    fn ts_js_generated() {
        assert!(is_generated_file("src/api/types.generated.ts"));
        assert!(is_generated_file("src/graphql.g.ts"));
        assert!(is_generated_file("src/__generated__/schema.ts"));
        assert!(is_generated_file("dist/bundle.js"));
        assert!(is_generated_file(".next/server/app.js"));
        assert!(is_generated_file(".nuxt/types.ts"));
    }

    #[test]
    fn python_generated() {
        assert!(is_generated_file("proto/service_pb2.py"));
        assert!(is_generated_file("proto/service_pb2_grpc.py"));
        assert!(is_generated_file("models/user_generated.py"));
    }

    #[test]
    fn c_cpp_generated() {
        assert!(is_generated_file("proto/msg.pb.h"));
        assert!(is_generated_file("proto/msg.pb.cc"));
        assert!(is_generated_file("proto/svc.grpc.pb.h"));
        assert!(is_generated_file("build/moc_widget.cpp"));
        assert!(is_generated_file("build/ui_mainwindow.h"));
        assert!(is_generated_file("parser.tab.c"));
        assert!(is_generated_file("lex.yy.c"));
    }

    #[test]
    fn csharp_generated() {
        assert!(is_generated_file("Views/Main.Designer.cs"));
        assert!(is_generated_file("Generated/Types.g.cs"));
        assert!(is_generated_file("Data/Types.generated.cs"));
        assert!(is_generated_file("Migrations/20230101_Init.cs"));
    }

    #[test]
    fn java_generated() {
        assert!(is_generated_file(
            "target/generated-sources/annotations/Foo.java"
        ));
        assert!(is_generated_file(
            "build/generated/source/proto/main/Svc.java"
        ));
    }

    #[test]
    fn swift_generated() {
        assert!(is_generated_file("Sources/Mock.generated.swift"));
        assert!(is_generated_file("Generated/AutoEquatable.swift"));
    }

    #[test]
    fn dart_generated() {
        assert!(is_generated_file("lib/model.g.dart"));
        assert!(is_generated_file("lib/model.freezed.dart"));
    }

    #[test]
    fn rust_build_output() {
        assert!(is_generated_file(
            "target/debug/build/serde-abc123/out/generated.rs"
        ));
    }

    #[test]
    fn vendor_and_node_modules() {
        assert!(is_generated_file("vendor/github.com/pkg/errors/errors.go"));
        assert!(is_generated_file("node_modules/lodash/index.js"));
        assert!(is_generated_file("__pycache__/module.cpython-311.pyc"));
    }

    #[test]
    fn windows_path_separators() {
        assert!(is_generated_file(r"proto\service.pb.go"));
        assert!(is_generated_file(r"src\__generated__\schema.ts"));
        assert!(is_generated_file(r"vendor\github.com\pkg\errors.go"));
    }

    // --- Negative cases (should NOT be detected as generated) ---

    #[test]
    fn normal_go_files() {
        assert!(!is_generated_file("cmd/server/main.go"));
        assert!(!is_generated_file("internal/handler/user.go"));
        assert!(!is_generated_file("pkg/service/auth.go"));
    }

    #[test]
    fn normal_ts_files() {
        assert!(!is_generated_file("src/components/Button.tsx"));
        assert!(!is_generated_file("src/utils/format.ts"));
        assert!(!is_generated_file("src/index.ts"));
    }

    #[test]
    fn normal_python_files() {
        assert!(!is_generated_file("app/models/user.py"));
        assert!(!is_generated_file("tests/test_auth.py"));
    }

    #[test]
    fn normal_rust_files() {
        assert!(!is_generated_file("src/main.rs"));
        assert!(!is_generated_file("src/lib.rs"));
        assert!(!is_generated_file("src/parsing/mod.rs"));
    }

    #[test]
    fn normal_java_files() {
        assert!(!is_generated_file("src/main/java/com/app/Service.java"));
    }

    #[test]
    fn normal_csharp_files() {
        assert!(!is_generated_file("Controllers/UserController.cs"));
    }

    #[test]
    fn normal_swift_files() {
        assert!(!is_generated_file("Sources/App/AppDelegate.swift"));
    }

    #[test]
    fn normal_dart_files() {
        assert!(!is_generated_file("lib/main.dart"));
        assert!(!is_generated_file("lib/models/user.dart"));
    }

    #[test]
    fn empty_path() {
        assert!(!is_generated_file(""));
    }
}
